# Generated by Django 3.1.7 on 2021-04-16 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Coin', 'Coin'), ('Banknote', 'Banknote')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('code', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('country', models.CharField(max_length=200, null=True)),
                ('denomination', models.IntegerField(null=True)),
                ('quality', models.CharField(max_length=200, null=True)),
                ('series', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('test', models.CharField(blank=True, max_length=200, null=True)),
                ('test2', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custom_user.customuser')),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
