# Generated by Django 3.1.7 on 2021-04-25 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Coin', 'Coin'), ('Banknote', 'Banknote')], max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.IntegerField(null=True)),
                ('release_date', models.DateField(null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('denomination', models.IntegerField(null=True)),
                ('quality', models.CharField(choices=[('Mint', 'Mint'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Fair', 'Fair'), ('Poor', 'Poor')], max_length=200, null=True)),
                ('series', models.CharField(max_length=200, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
    ]
