# Generated by Django 3.1.7 on 2021-04-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='test3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
