# Generated by Django 3.1.7 on 2021-05-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
        ('currency', '0002_auto_20210514_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='collection',
            field=models.ManyToManyField(to='collection.Collection'),
        ),
    ]
