# Generated by Django 3.1.7 on 2021-04-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_currency_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
