# Generated by Django 3.1.7 on 2021-05-30 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_currency_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='collection',
        ),
    ]
